name: Auto Tweet

on:
  schedule:
    - cron: "00 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install twikit

    - name: Run Tweet Bot
      env:
        TW_USERNAME: ${{ secrets.TW_USERNAME }}
        TW_EMAIL: ${{ secrets.TW_EMAIL }}
        TW_PASSWORD: ${{ secrets.TW_PASSWORD }}
      run: python tweet_bot.py
